version: '3.8'
services:
  payment-api:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=ameday-payment 