version: '3.8'

services:
  payment-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./fuel/app/logs:/app/fuel/app/logs
      - ./fuel/app/cache:/app/fuel/app/cache
    expose:
      - "9000"
    environment:
      - FUEL_ENV=${FUEL_ENV:-development}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY:-your key}
      - NEW_RELIC_APP_NAME=local-payment
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./public:/app/public
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payment-api
    restart: unless-stopped 